
trigger:
  branches:
    include:
      - main

pool:
  name: Default
  demands:
    - agent.name -equals DESKTOP-LPAPBRT

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Publicar projeto'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: 'Deploy para Azure App Service'
  inputs:
    azureSubscription: 'acr-connection'
    appType: 'webApp'
    appName: 'cloudgames-api'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
