name: Build and Test ASP.NET Core 8 API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore CloudGames/CloudGamesAPI.csproj

    - name: Build
      run: dotnet build CloudGames/CloudGamesAPI.csproj --no-restore --configuration Release
